/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Frequency = IDL.Variant({
  'unlimited' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Child = IDL.Record({
  'id' : IDL.Principal,
  'balance' : IDL.Int,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'avatar' : IDL.Text,
});
export const Chore = IDL.Record({
  'id' : IDL.Nat,
  'reward' : IDL.Int,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'frequency' : Frequency,
});
export const CompletionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const ChoreCompletion = IDL.Record({
  'id' : IDL.Nat,
  'status' : CompletionStatus,
  'reward' : IDL.Int,
  'childId' : IDL.Principal,
  'timestamp' : Time,
  'choreId' : IDL.Nat,
  'verifiedBy' : IDL.Opt(IDL.Principal),
});
export const Deduction = IDL.Record({
  'id' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'childId' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Int,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeduction' : IDL.Func([IDL.Principal, IDL.Int, IDL.Text], [IDL.Nat], []),
  'approveCompletion' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChild' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Principal],
      [],
    ),
  'createChore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, Frequency],
      [IDL.Nat],
      [],
    ),
  'deleteChild' : IDL.Func([IDL.Principal], [], []),
  'deleteChore' : IDL.Func([IDL.Nat], [], []),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChild' : IDL.Func([IDL.Principal], [IDL.Opt(Child)], ['query']),
  'getChore' : IDL.Func([IDL.Nat], [IDL.Opt(Chore)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'completions' : IDL.Vec(ChoreCompletion),
          'deductions' : IDL.Vec(Deduction),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
  'listChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
  'listPendingCompletions' : IDL.Func(
      [],
      [IDL.Vec(ChoreCompletion)],
      ['query'],
    ),
  'markChoreComplete' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'rejectCompletion' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Frequency = IDL.Variant({
    'unlimited' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Child = IDL.Record({
    'id' : IDL.Principal,
    'balance' : IDL.Int,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'avatar' : IDL.Text,
  });
  const Chore = IDL.Record({
    'id' : IDL.Nat,
    'reward' : IDL.Int,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'frequency' : Frequency,
  });
  const CompletionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChoreCompletion = IDL.Record({
    'id' : IDL.Nat,
    'status' : CompletionStatus,
    'reward' : IDL.Int,
    'childId' : IDL.Principal,
    'timestamp' : Time,
    'choreId' : IDL.Nat,
    'verifiedBy' : IDL.Opt(IDL.Principal),
  });
  const Deduction = IDL.Record({
    'id' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'childId' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Int,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeduction' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveCompletion' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChild' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'createChore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, Frequency],
        [IDL.Nat],
        [],
      ),
    'deleteChild' : IDL.Func([IDL.Principal], [], []),
    'deleteChore' : IDL.Func([IDL.Nat], [], []),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChild' : IDL.Func([IDL.Principal], [IDL.Opt(Child)], ['query']),
    'getChore' : IDL.Func([IDL.Nat], [IDL.Opt(Chore)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'completions' : IDL.Vec(ChoreCompletion),
            'deductions' : IDL.Vec(Deduction),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChildren' : IDL.Func([], [IDL.Vec(Child)], ['query']),
    'listChores' : IDL.Func([], [IDL.Vec(Chore)], ['query']),
    'listPendingCompletions' : IDL.Func(
        [],
        [IDL.Vec(ChoreCompletion)],
        ['query'],
      ),
    'markChoreComplete' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'rejectCompletion' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };