/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Child {
  'id' : Principal,
  'balance' : bigint,
  'name' : string,
  'createdBy' : Principal,
  'avatar' : string,
}
export interface Chore {
  'id' : bigint,
  'reward' : bigint,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'frequency' : Frequency,
}
export interface ChoreCompletion {
  'id' : bigint,
  'status' : CompletionStatus,
  'reward' : bigint,
  'childId' : Principal,
  'timestamp' : Time,
  'choreId' : bigint,
  'verifiedBy' : [] | [Principal],
}
export type CompletionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Deduction {
  'id' : bigint,
  'createdBy' : Principal,
  'childId' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
  'reason' : string,
}
export type Frequency = { 'unlimited' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeduction' : ActorMethod<[Principal, bigint, string], bigint>,
  'approveCompletion' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChild' : ActorMethod<[Principal, string, string], Principal>,
  'createChore' : ActorMethod<[string, string, bigint, Frequency], bigint>,
  'deleteChild' : ActorMethod<[Principal], undefined>,
  'deleteChore' : ActorMethod<[bigint], undefined>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChild' : ActorMethod<[Principal], [] | [Child]>,
  'getChore' : ActorMethod<[bigint], [] | [Chore]>,
  'getTransactionHistory' : ActorMethod<
    [Principal],
    { 'completions' : Array<ChoreCompletion>, 'deductions' : Array<Deduction> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChildren' : ActorMethod<[], Array<Child>>,
  'listChores' : ActorMethod<[], Array<Chore>>,
  'listPendingCompletions' : ActorMethod<[], Array<ChoreCompletion>>,
  'markChoreComplete' : ActorMethod<[bigint], bigint>,
  'rejectCompletion' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];